# Generated by Django 6.0.2 on 2026-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField()),
                ('press', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('suitability', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('suitability_reason', models.TextField()),
                ('case_category', models.CharField(max_length=100)),
                ('defendant', models.CharField(max_length=200)),
                ('damage_scale', models.TextField()),
                ('stage', models.CharField(max_length=50)),
                ('stage_detail', models.CharField(max_length=200)),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
