# Generated by Django 6.0.2 on 2026-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_case_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
