# Generated by Django 6.0.2 on 2026-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_skippedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='region',
            field=models.CharField(choices=[('국내', '국내'), ('해외', '해외')], db_index=True, default='국내', max_length=10),
        ),
    ]
