# Generated by Django 6.0.2 on 2026-02-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='skippedurl',
            name='press',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skippedurl',
            name='related_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_articles', to='articles.article'),
        ),
        migrations.AddField(
            model_name='skippedurl',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
