# Generated by Django 6.0.2 on 2026-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_skippedurl_press_skippedurl_related_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='review_passed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
