# Generated by Django 6.0.2 on 2026-03-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_is_reviewed_article_review_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='articles.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
