# Generated by Django 6.0.2 on 2026-03-03 11:09

from django.db import migrations, models


def copy_suitability_to_ai(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    Article.objects.update(ai_suitability=models.F('suitability'))


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlememo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlememo',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='ai_suitability',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='', max_length=10),
        ),
        migrations.RunPython(copy_suitability_to_ai, migrations.RunPython.noop),
    ]
